// Code generated by fuego. DO NOT EDIT.
// This file is automatically regenerated when routes change.
// Generator schema version: 1

package main

import (
	"github.com/abdul-hamid-achik/fuego/pkg/fuego"

	login_page "github.com/abdul-hamid-achik/fuego-cloud/app/_auth_/login"
	app_page "github.com/abdul-hamid-achik/fuego-cloud/app"
	callback "github.com/abdul-hamid-achik/fuego-cloud/app/_auth_/callback"
	logout "github.com/abdul-hamid-achik/fuego-cloud/app/_auth_/logout"
	id "github.com/abdul-hamid-achik/fuego-cloud/app/api/apps/_name/deployments/_id"
	verify "github.com/abdul-hamid-achik/fuego-cloud/app/api/apps/_name/domains/_domain/verify"
	domains "github.com/abdul-hamid-achik/fuego-cloud/app/api/apps/_name/domains"
	env "github.com/abdul-hamid-achik/fuego-cloud/app/api/apps/_name/env"
	logs "github.com/abdul-hamid-achik/fuego-cloud/app/api/apps/_name/logs"
	callback2 "github.com/abdul-hamid-achik/fuego-cloud/app/api/auth/callback"
	deployments "github.com/abdul-hamid-achik/fuego-cloud/app/api/apps/_name/deployments"
	restart "github.com/abdul-hamid-achik/fuego-cloud/app/api/apps/_name/restart"
	auth "github.com/abdul-hamid-achik/fuego-cloud/app/api/auth"
	token "github.com/abdul-hamid-achik/fuego-cloud/app/api/auth/token"
	health "github.com/abdul-hamid-achik/fuego-cloud/app/api/health"
	token2 "github.com/abdul-hamid-achik/fuego-cloud/app/api/registry/token"
	me "github.com/abdul-hamid-achik/fuego-cloud/app/api/users/me"
	apps2 "github.com/abdul-hamid-achik/fuego-cloud/app/dashboard/apps"
	activity "github.com/abdul-hamid-achik/fuego-cloud/app/api/apps/_name/activity"
	domain "github.com/abdul-hamid-achik/fuego-cloud/app/api/apps/_name/domains/_domain"
	metrics "github.com/abdul-hamid-achik/fuego-cloud/app/api/apps/_name/metrics"
	name "github.com/abdul-hamid-achik/fuego-cloud/app/api/apps/_name"
	scale "github.com/abdul-hamid-achik/fuego-cloud/app/api/apps/_name/scale"
	metrics2 "github.com/abdul-hamid-achik/fuego-cloud/app/api/metrics"
	apps "github.com/abdul-hamid-achik/fuego-cloud/app/api/apps"
	name2 "github.com/abdul-hamid-achik/fuego-cloud/app/dashboard/apps/_name"
	dashboard "github.com/abdul-hamid-achik/fuego-cloud/app/dashboard"
)

// RegisterRoutes registers all file-based routes with the app.
func RegisterRoutes(app *fuego.App) {

	// GET /callback (from app/_auth_/callback/route.go)
	app.RegisterRoute("GET", "/callback", callback.Get)
	// POST /logout (from app/_auth_/logout/route.go)
	app.RegisterRoute("POST", "/logout", logout.Post)
	// GET /logout (from app/_auth_/logout/route.go)
	app.RegisterRoute("GET", "/logout", logout.Get)
	// GET /api/apps/{name}/activity (from app/api/apps/_name/activity/route.go)
	app.RegisterRoute("GET", "/api/apps/{name}/activity", activity.Get)
	// GET /api/apps/{name}/deployments/{id} (from app/api/apps/_name/deployments/_id/route.go)
	app.RegisterRoute("GET", "/api/apps/{name}/deployments/{id}", id.Get)
	// POST /api/apps/{name}/deployments/{id} (from app/api/apps/_name/deployments/_id/route.go)
	app.RegisterRoute("POST", "/api/apps/{name}/deployments/{id}", id.Post)
	// GET /api/apps/{name}/deployments (from app/api/apps/_name/deployments/route.go)
	app.RegisterRoute("GET", "/api/apps/{name}/deployments", deployments.Get)
	// POST /api/apps/{name}/deployments (from app/api/apps/_name/deployments/route.go)
	app.RegisterRoute("POST", "/api/apps/{name}/deployments", deployments.Post)
	// GET /api/apps/{name}/domains/{domain} (from app/api/apps/_name/domains/_domain/route.go)
	app.RegisterRoute("GET", "/api/apps/{name}/domains/{domain}", domain.Get)
	// DELETE /api/apps/{name}/domains/{domain} (from app/api/apps/_name/domains/_domain/route.go)
	app.RegisterRoute("DELETE", "/api/apps/{name}/domains/{domain}", domain.Delete)
	// POST /api/apps/{name}/domains/{domain}/verify (from app/api/apps/_name/domains/_domain/verify/route.go)
	app.RegisterRoute("POST", "/api/apps/{name}/domains/{domain}/verify", verify.Post)
	// GET /api/apps/{name}/domains (from app/api/apps/_name/domains/route.go)
	app.RegisterRoute("GET", "/api/apps/{name}/domains", domains.Get)
	// POST /api/apps/{name}/domains (from app/api/apps/_name/domains/route.go)
	app.RegisterRoute("POST", "/api/apps/{name}/domains", domains.Post)
	// GET /api/apps/{name}/env (from app/api/apps/_name/env/route.go)
	app.RegisterRoute("GET", "/api/apps/{name}/env", env.Get)
	// PUT /api/apps/{name}/env (from app/api/apps/_name/env/route.go)
	app.RegisterRoute("PUT", "/api/apps/{name}/env", env.Put)
	// GET /api/apps/{name}/logs (from app/api/apps/_name/logs/route.go)
	app.RegisterRoute("GET", "/api/apps/{name}/logs", logs.Get)
	// GET /api/apps/{name}/metrics (from app/api/apps/_name/metrics/route.go)
	app.RegisterRoute("GET", "/api/apps/{name}/metrics", metrics.Get)
	// POST /api/apps/{name}/restart (from app/api/apps/_name/restart/route.go)
	app.RegisterRoute("POST", "/api/apps/{name}/restart", restart.Post)
	// GET /api/apps/{name} (from app/api/apps/_name/route.go)
	app.RegisterRoute("GET", "/api/apps/{name}", name.Get)
	// PUT /api/apps/{name} (from app/api/apps/_name/route.go)
	app.RegisterRoute("PUT", "/api/apps/{name}", name.Put)
	// DELETE /api/apps/{name} (from app/api/apps/_name/route.go)
	app.RegisterRoute("DELETE", "/api/apps/{name}", name.Delete)
	// POST /api/apps/{name}/scale (from app/api/apps/_name/scale/route.go)
	app.RegisterRoute("POST", "/api/apps/{name}/scale", scale.Post)
	// GET /api/apps/{name}/scale (from app/api/apps/_name/scale/route.go)
	app.RegisterRoute("GET", "/api/apps/{name}/scale", scale.Get)
	// GET /api/apps (from app/api/apps/route.go)
	app.RegisterRoute("GET", "/api/apps", apps.Get)
	// POST /api/apps (from app/api/apps/route.go)
	app.RegisterRoute("POST", "/api/apps", apps.Post)
	// GET /api/auth/callback (from app/api/auth/callback/route.go)
	app.RegisterRoute("GET", "/api/auth/callback", callback2.Get)
	// GET /api/auth (from app/api/auth/route.go)
	app.RegisterRoute("GET", "/api/auth", auth.Get)
	// POST /api/auth/token (from app/api/auth/token/route.go)
	app.RegisterRoute("POST", "/api/auth/token", token.Post)
	// GET /api/auth/token (from app/api/auth/token/route.go)
	app.RegisterRoute("GET", "/api/auth/token", token.Get)
	// GET /api/health (from app/api/health/route.go)
	app.RegisterRoute("GET", "/api/health", health.Get)
	// GET /api/metrics (from app/api/metrics/route.go)
	app.RegisterRoute("GET", "/api/metrics", metrics2.Get)
	// GET /api/registry/token (from app/api/registry/token/route.go)
	app.RegisterRoute("GET", "/api/registry/token", token2.Get)
	// POST /api/registry/token (from app/api/registry/token/route.go)
	app.RegisterRoute("POST", "/api/registry/token", token2.Post)
	// DELETE /api/registry/token (from app/api/registry/token/route.go)
	app.RegisterRoute("DELETE", "/api/registry/token", token2.Delete)
	// GET /api/users/me (from app/api/users/me/route.go)
	app.RegisterRoute("GET", "/api/users/me", me.Get)
	// PUT /api/users/me (from app/api/users/me/route.go)
	app.RegisterRoute("PUT", "/api/users/me", me.Put)
	// GET /dashboard/apps/{name} (from app/dashboard/apps/_name/route.go)
	app.RegisterRoute("GET", "/dashboard/apps/{name}", name2.Get)
	// GET /dashboard/apps (from app/dashboard/apps/route.go)
	app.RegisterRoute("GET", "/dashboard/apps", apps2.Get)
	// GET /dashboard (from app/dashboard/route.go)
	app.RegisterRoute("GET", "/dashboard", dashboard.Get)
	// Page: /login (from app/_auth_/login/page.templ)
	app.Get("/login", func(c *fuego.Context) error {
		return fuego.TemplComponent(c, 200, login_page.Page())
	})
	// Page: / (from app/page.templ)
	app.Get("/", func(c *fuego.Context) error {
		return fuego.TemplComponent(c, 200, app_page.Page())
	})
}
